######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 21 08:26:43 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h sudokuwidget.h
SOURCES += main.cpp mainwindow.cpp sudokuwidget.cpp
INCLUDEPATH += /Qwt-5.2.1/include
LIBS += -L./ \
    -lqwt5
