######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 21 08:26:43 2010
######################################################################

QT       += core gui widgets
TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h sudokuwidget.h
SOURCES += main.cpp mainwindow.cpp sudokuwidget.cpp

LIBS += -L./ \
    -lqwt
